# This is a basic workflow to help you get started with Actions

name: Compilar App .NET

# Controls when the action will run. 
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Preparar .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 2.2.104
    - name: Construir app
      run: dotnet build
